
import sys, os
from binGenerator import buildBin
from main import build, DebugFlags

if __name__ == "__main__":
    fileName = ""

    if len(sys.argv) < 2:
        print("Please input an input file to run.")
        exit(1)
    else:
        fileName = sys.argv[1]
    ogDir = os.getcwd()
    with open(fileName, 'r') as f:

        outputFile = open(".".join(fileName.split(".")[:-1]) + ".starpc", "w")
        os.chdir(os.path.dirname(os.path.abspath(sys.argv[1])))
        outputtedAssembly = build(f.read(), filePath=fileName)
        if DebugFlags.showBytecode:
            print("================== GENERATED BYTECODE ==================")
            print(outputtedAssembly)

        outputFile.write(outputtedAssembly)
        outputFile.close()

    os.chdir(ogDir)
    buildBin(fileName=fileName + "c")
    print("Successfully compiled.")
    